"""Knowledge Workflow Engine.

Implements the user's desired knowledge base workflow:
1. Extract a task Key from user request (via lightweight LLM call)
2. Code-level comparison against stored knowledge base entries
3. If match found: ask user to reuse or re-execute
4. After task completion: prompt to save/update knowledge base
"""

from typing import Any
import re

from loguru import logger

from nanobot.agent.i18n import msg
from nanobot.agent.task_knowledge import TaskKnowledgeStore, tokenize_key
from nanobot.agent.hybrid_retriever import hybrid_retrieve
from nanobot.utils.metrics import metrics


# --- User command recognition ---
# All recognized forms of "use knowledge base" commands
_USE_COMMANDS = {
    # Chinese
    "直接用", "用知识库", "用", "使用知识库", "使用", "直接使用",
    # English
    "use", "reuse", "yes",
}

# All recognized forms of "re-execute" commands
_REDO_COMMANDS = {
    # Chinese
    "重新执行", "重新", "重新处理", "重做",
    # English
    "redo", "re-execute", "rerun", "again",
}

# All recognized forms of "save confirmation" commands
_SAVE_COMMANDS = {
    # Chinese
    "是", "好", "是的", "好的", "保存", "存",
    # English
    "yes", "ok", "save", "y",
}

# All recognized forms of "upgrade to skill" commands
_UPGRADE_COMMANDS = {
    # Chinese
    "升级", "升级skill", "升",
    # English
    "upgrade", "upgrade skill",
}


class KnowledgeWorkflow:
    """Knowledge base workflow engine.

    Responsibilities:
    1. Call lightweight LLM to extract a Key from user request
       (Chinese ≤50 chars, English ≤200 chars)
    2. Code-level comparison of Key against knowledge base entries
       (exact match → substring match → common-word similarity)
    3. Format prompts for user interaction
    4. Save/update knowledge base entries
    """

    def __init__(
        self,
        provider: Any = None,
        model: str | None = None,
        workspace: Any = None,
        vector_memory: Any = None,
    ):
        self.provider = provider
        self.model = model
        self.workspace = workspace
        self.knowledge_store = TaskKnowledgeStore(workspace) if workspace else None
        self.vector_memory = vector_memory  # P3: optional ChromaDB semantic fallback

    # ----------------------------------------------------------------
    # 1. Key Extraction (lightweight LLM call)
    # ----------------------------------------------------------------

    async def extract_key(self, user_request: str, history: list[dict] | None = None) -> str:
        """Extract a task key from user request using a lightweight LLM call.

        The key should be:
        - Chinese: ≤50 characters
        - English: ≤200 characters
        - A concise description of the task's core intent

        Returns:
            Extracted key string, or a truncated version of the request as fallback.
        """
        if not self.provider:
            return self._fallback_key(user_request)

        prompt_parts = [
            "Extract a concise task description from the user request below. ",
            "Rules:\n",
            "- If the request is in Chinese, output ≤50 Chinese characters\n",
            "- If the request is in English, output ≤200 English characters\n",
            "- Output ONLY the key text, nothing else\n",
            "- Focus on the core action and target\n",
        ]

        if history:
            prompt_parts.append("\nRecent conversation history (for context and coreference resolution):\n")
            # Only include the last 5 turns to save tokens
            for msg in history[-5:]:
                role = msg.get("role", "unknown")
                content = msg.get("content", "")
                # Only take text content up to 500 chars per message to avoid bloat
                if isinstance(content, str):
                    prompt_parts.append(f"[{role}]: {content[:500]}\n")
                elif isinstance(content, list):
                    # Handle multimodal content simply
                    text_parts = [b.get("text", "") for b in content if b.get("type") == "text"]
                    text_content = " ".join(text_parts)
                    prompt_parts.append(f"[{role}]: {text_content[:500]}\n")

        prompt_parts.append(f"\nUser request: {user_request}\n\nKey:")
        prompt = "".join(prompt_parts)

        try:
            response = await self.provider.chat(
                messages=[{"role": "user", "content": prompt}],
                model=self.model,
                temperature=0.1,
                max_tokens=100,
            )
            content = response.content or ""
            # Strip <think>...</think> tags which are generated by reasoning models
            content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL)
            key = content.strip().strip('"').strip("'")
            if key:
                logger.info(f"KnowledgeWorkflow: extracted key = '{key}'")
                return key
        except Exception as e:
            logger.warning(f"KnowledgeWorkflow: key extraction failed: {e}")

        return self._fallback_key(user_request)

    def _fallback_key(self, user_request: str) -> str:
        """Fallback key extraction without LLM — simple truncation."""
        # Heuristic: if mostly CJK chars, limit to 50; otherwise 200
        cjk_count = sum(1 for c in user_request if '\u4e00' <= c <= '\u9fff')
        limit = 50 if cjk_count > len(user_request) * 0.3 else 200
        return user_request[:limit].strip()

    # ----------------------------------------------------------------
    # 2. Knowledge Base Matching (pure code, no LLM)
    # ----------------------------------------------------------------

    def match_knowledge(self, key: str) -> dict[str, Any] | None:
        """Match extracted key against knowledge base entries.

        Matching strategy (in order of priority):
        1. Exact match (key strings identical)
        2. Substring match (one key contains the other)
        3. Common-word similarity (>= 50% shared words)

        Returns:
            Matched task entry dict, or None if no match found.
        """
        if not self.knowledge_store:
            return None

        tasks = self.knowledge_store.get_all_tasks()
        if not tasks:
            return None

        key_lower = key.lower().strip()

        # Pass 1: Exact match
        for task in tasks:
            task_key = task.get("key", "").lower().strip()
            if task_key == key_lower:
                logger.info(f"KnowledgeWorkflow: exact match found: '{task_key}'")
                return task

        # Pass 2: Substring match
        best_substring: dict | None = None
        best_ratio = 0.0
        for task in tasks:
            task_key = task.get("key", "").lower().strip()
            if not task_key:
                continue
            if key_lower in task_key or task_key in key_lower:
                shorter = min(len(key_lower), len(task_key))
                longer = max(len(key_lower), len(task_key))
                ratio = shorter / longer if longer > 0 else 0
                if ratio > best_ratio:
                    best_ratio = ratio
                    best_substring = task
        if best_substring and best_ratio >= 0.5:
            logger.info(
                f"KnowledgeWorkflow: substring match found: "
                f"'{best_substring.get('key')}' (ratio={best_ratio:.2f})"
            )
            return best_substring

        # Pass 3: True Hybrid Retrieval (Dense + BM25)
        best_hybrid_match, best_hybrid_score = hybrid_retrieve(
            query=key,
            candidates=tasks,
            text_field="key",
            extra_text_field="triggers",
            match_key_field="key",
            vector_memory=self.vector_memory if self.knowledge_store else None,
            vector_source_filter="knowledge",
            threshold=0.6,
        )

        if best_hybrid_match:
            logger.info(
                f"KnowledgeWorkflow: hybrid match found: "
                f"'{best_hybrid_match.get('key')}' (score={best_hybrid_score:.2f})"
            )
            return best_hybrid_match

        logger.debug(f"KnowledgeWorkflow: no match found for key '{key}'")
        return None

    def match_experience(self, action_context: str) -> str | None:
        """Find action-level tactical prompts from the Experience Bank (P12 feature).
        
        Args:
            action_context: The current context of the agent's action (e.g., tool name, error message).
             
        Returns:
            A tactical prompt string to inject, or None.
        """
        if not self.knowledge_store:
            return None
            
        experiences = self.knowledge_store.get_experiences()
        if not experiences:
            return None

        # Hybrid Retrieval (Dense + BM25) for Experiences
        best_match, best_score = hybrid_retrieve(
            query=action_context,
            candidates=experiences,
            text_field="trigger",
            extra_text_field=None,
            match_key_field="trigger",
            vector_memory=self.vector_memory if self.knowledge_store else None,
            vector_source_filter="knowledge_experience",
            threshold=0.4,
            no_dense_penalty=1.0,  # Don't penalize experience matches without dense scores
        )

        if best_match:
            logger.info(
                f"KnowledgeWorkflow: experience match found: "
                f"'{best_match.get('trigger')}' (score={best_score:.2f})"
            )
            return best_match.get("prompt")
            
        return None

    def _tokenize(self, text: str) -> list[str]:
        """Tokenize text for word-similarity matching.

        Delegates to the shared tokenize_key() function in task_knowledge.
        """
        return tokenize_key(text)

    # ----------------------------------------------------------------
    # 3. User Command Recognition
    # ----------------------------------------------------------------

    @staticmethod
    def is_use_command(text: str) -> bool:
        """Check if user input means 'use knowledge base result'."""
        return text.strip().lower() in _USE_COMMANDS

    @staticmethod
    def is_redo_command(text: str) -> bool:
        """Check if user input means 're-execute the task'."""
        return text.strip().lower() in _REDO_COMMANDS

    @staticmethod
    def is_save_confirm(text: str) -> bool:
        """Check if user input means 'confirm save to knowledge base'."""
        return text.strip().lower() in _SAVE_COMMANDS

    @staticmethod
    def is_upgrade_command(text: str) -> bool:
        """Check if user input means 'confirm skill upgrade'."""
        return text.strip().lower() in _UPGRADE_COMMANDS
    # ----------------------------------------------------------------
    # 4. Prompt Formatting
    # ----------------------------------------------------------------

    @staticmethod
    def format_match_prompt(match: dict, lang: str | None = None) -> str:
        """Format the knowledge-match prompt for the user."""
        key = match.get("key", "unknown")
        return msg("knowledge_match_prompt", lang=lang, key=key)

    @staticmethod
    def format_save_prompt(lang: str | None = None) -> str:
        """Format the save-to-knowledge-base prompt."""
        return msg("save_prompt", lang=lang)

    @staticmethod
    def format_save_confirmed(lang: str | None = None) -> str:
        """Format the save-confirmed message."""
        return msg("save_confirmed", lang=lang)

    # ----------------------------------------------------------------
    # 5. Knowledge Base Save / Update
    # ----------------------------------------------------------------

    async def save_to_knowledge(
        self,
        key: str,
        steps: list[dict],
        user_request: str,
        result_summary: str = "",
    ) -> bool:
        """Save or update a task in the knowledge base.

        Strategy (P0 — auto-merge):
        1. Exact key match → merge into existing entry (version++)
        2. Similar key found → merge into similar entry (avoid duplicates)
        3. No match → create new entry

        Args:
            key: Task key (extracted by extract_key).
            steps: List of tool call dicts [{tool, args}, ...].
            user_request: Original user request text.
            result_summary: Summary of the task result.

        Returns:
            True if saved successfully.
        """
        if not self.knowledge_store:
            logger.warning("KnowledgeWorkflow: no knowledge store available")
            return False

        try:
            # Phase 12: Knowledge Judge evaluation (LLM)
            judge_result = await self.evaluate_and_structure_knowledge(key, user_request, steps, result_summary)
            decision = judge_result.get("decision", "ADD")
            
            if decision == "DISCARD":
                logger.info(f"KnowledgeWorkflow Judge: discarded new knowledge for '{key}'")
                return True

            triggers = judge_result.get("triggers", [])
            tags = judge_result.get("tags", [])
            anti_patterns = judge_result.get("anti_patterns", [])
            confidence = judge_result.get("confidence", 1.0)

            # 1. Exact key match → merge
            existing = self.knowledge_store.find_task(key)
            if existing or decision == "MERGE":
                target_key = existing.get("key") if existing else key
                # If decision was MERGE but exact key didn't match, try to find a similar one
                if not existing and decision == "MERGE":
                    similar = self.knowledge_store.find_similar_task(key)
                    if similar:
                        target_key = similar.get("key", key)
                        
                self.knowledge_store.merge_task(
                    existing_key=target_key,
                    new_steps=steps,
                    new_result_summary=result_summary or "Task completed",
                    new_steps_detail=steps,
                    new_triggers=triggers,
                    new_tags=tags,
                    new_anti_patterns=anti_patterns,
                    new_confidence=confidence,
                )
                logger.info(f"KnowledgeWorkflow: merged for key='{target_key}'")
                return True

            # 2. Similar key match → merge (fallback if judge said ADD but there's a very similar one)
            similar = self.knowledge_store.find_similar_task(key)
            if similar:
                similar_key = similar.get("key", "")
                self.knowledge_store.merge_task(
                    existing_key=similar_key,
                    new_steps=steps,
                    new_result_summary=result_summary or "Task completed",
                    new_steps_detail=steps,
                    new_triggers=triggers,
                    new_tags=tags,
                    new_anti_patterns=anti_patterns,
                    new_confidence=confidence,
                )
                logger.info(f"KnowledgeWorkflow: merged (similar) '{key}' → '{similar_key}'")
                return True

            # 3. No match → create new
            self.knowledge_store.add_task(
                key=key,
                description=user_request[:100],
                steps=steps,
                params={},
                result_summary=result_summary or "Task completed",
                triggers=triggers,
                tags=tags,
                anti_patterns=anti_patterns,
                confidence=confidence,
            )
            logger.info(f"KnowledgeWorkflow: saved new knowledge for key='{key}'")
            return True
        except Exception as e:
            logger.error(f"KnowledgeWorkflow: save failed: {e}")
            metrics.increment("knowledge_save_error_count")
            return False

    async def evaluate_and_structure_knowledge(self, key: str, request: str, steps: list[dict], result: str) -> dict[str, Any]:
        """Evaluate new knowledge using LLM and structure it into formal fields.
        
        Returns a dict:
            decision: "ADD", "MERGE", or "DISCARD"
            triggers: list of strings
            tags: list of strings
            anti_patterns: list of strings
            confidence: float (0.0 - 1.0)
        """
        default_result = {
            "decision": "ADD",
            "triggers": [key],
            "tags": [],
            "anti_patterns": [],
            "confidence": 0.8
        }
        
        if not self.provider:
            return default_result
            
        # Format the task representation
        task_str = f"Task Key: {key}\nOriginal Request: {request}\nSteps: {steps}\nResult: {result}"
        
        prompt = f"""
You are the Knowledge Management Judge for a personal AI assistant.
Your job is to evaluate a newly completed workflow and structure it for the Knowledge Base.

Workflow Data:
{task_str}

Tasks:
1. DECISION: Decide if this knowledge should be ADDed as new, MERGEd with existing, or DISCARDed entirely (if trivial, completely erroneous, or empty).
2. TRIGGERS: Extract 2-3 short, distinct trigger phrases the user might say next time to request this.
3. TAGS: 1-3 broad categorization tags (e.g., 'email', 'system', 'research').
4. ANTI-PATTERNS: 1-2 warnings or mistakes to avoid when running this workflow in the future (based on the steps or result). If none, empty array.
5. CONFIDENCE: Give a confidence score (0.0 to 1.0) on how reliable and generalizable this workflow is.

Return your evaluation EXACTLY as a JSON object, with no markdown formatting around it:
{{
    "decision": "ADD|MERGE|DISCARD",
    "triggers": ["trigger1", "trigger2"],
    "tags": ["tag1", "tag2"],
    "anti_patterns": ["anti_pattern1"],
    "confidence": 0.9
}}
"""
        import json
        try:
            response = await self.provider.chat(
                messages=[{"role": "user", "content": prompt}],
                model=self.model,
                temperature=0.1,
                max_tokens=300,
            )
            content = response.content or ""
            # Strip markdown and any <think> tags
            content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL)
            content = content.replace("```json", "").replace("```", "").strip()
            parsed = json.loads(content)
            
            # Merge with defaults to ensure all keys exist
            return {**default_result, **parsed}
        except Exception as e:
            logger.warning(f"Knowledge Judge failed, using defaults: {e}")
            metrics.increment("knowledge_judge_fallback_count")
            return default_result

    def get_knowledge_result(self, match: dict, lang: str | None = None) -> str:
        """Format and return the stored result of a matched knowledge entry.

        If the match has a result_summary, returns that.
        Otherwise returns step names.
        """
        result_summary = match.get("result_summary", "")
        if result_summary:
            return msg("knowledge_result_header", lang=lang, result=result_summary)

        # Fallback: list the steps
        steps = match.get("steps", [])
        if steps:
            step_names = []
            for s in steps:
                if isinstance(s, dict):
                    step_names.append(s.get("tool", str(s)))
                else:
                    step_names.append(str(s))
            steps_text = "\n".join(f"  {i+1}. {name}" for i, name in enumerate(step_names))
            return msg("knowledge_result_header", lang=lang, result=steps_text)

        return msg("knowledge_no_params", lang=lang)

    # ----------------------------------------------------------------
    # 6. Outcome Tracking (implicit feedback)
    # ----------------------------------------------------------------

    # Negative feedback patterns — if user's next message matches,
    # the previous task is recorded as a failure.
    _NEGATIVE_FEEDBACK = {
        # Chinese
        "不对", "错了", "重来", "重做", "不行", "有问题", "再试",
        # English
        "wrong", "incorrect", "redo", "try again", "not right", "fix it",
    }

    @classmethod
    def is_negative_feedback(cls, text: str) -> bool:
        """Check if user message implies the previous task failed."""
        t = text.strip().lower()
        return any(neg in t for neg in cls._NEGATIVE_FEEDBACK)

    def record_outcome(self, key: str, success: bool) -> None:
        """Record task outcome (success or failure) in knowledge base."""
        if not self.knowledge_store:
            return
        if success:
            self.knowledge_store.record_success(key)
            logger.info(f"KnowledgeWorkflow: recorded success for '{key}'")
        else:
            self.knowledge_store.record_failure(key)
            logger.info(f"KnowledgeWorkflow: recorded failure for '{key}'")

    # ----------------------------------------------------------------
    # 7. Few-shot Prompt Generation (for local model accuracy)
    # ----------------------------------------------------------------

    def format_few_shot_prompt(self, match: dict) -> str:
        """Generate a few-shot reference prompt from a high-success knowledge entry.

        This is injected into the system message when a user chooses "redo" on a
        matched task, giving the local LLM a reference path to follow.

        Returns:
            A formatted prompt string, or empty string if no useful detail available.
        """
        key = match.get("key", "")
        steps_detail = match.get("last_steps_detail", [])
        steps = match.get("steps", [])
        result_summary = match.get("result_summary", "")
        success_count = match.get("success_count", 0)
        use_count = match.get("use_count", 0)

        if not steps_detail and not steps:
            return ""

        lines = [
            f"## Reference: Previously successful execution of '{key}'",
            f"(Success: {success_count}/{use_count} executions)",
            "",
        ]

        if steps_detail:
            lines.append("### Steps taken:")
            for i, step in enumerate(steps_detail, 1):
                tool = step.get("tool", "unknown")
                args = step.get("args", {})
                result = step.get("result", "")
                args_str = ", ".join(f"{k}={v!r}" for k, v in args.items()) if isinstance(args, dict) else str(args)
                lines.append(f"{i}. `{tool}({args_str})`")
                if result:
                    lines.append(f"   → {result[:200]}")
        elif steps:
            lines.append("### Tools used:")
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    lines.append(f"{i}. `{step.get('tool', str(step))}`")
                else:
                    lines.append(f"{i}. `{step}`")

        if result_summary:
            lines.extend(["", f"### Final result: {result_summary}"])

        lines.extend([
            "",
            "Use this as a reference. Adapt parameters to the current request.",
        ])
        return "\n".join(lines)

    async def adapt_knowledge(self, match: dict, current_request: str, history: list[dict] | None = None) -> str:
        """Adapt a retrieved knowledge entry into a tailored few-shot prompt for the current context.

        This uses a lightweight LLM call to rewrite the generic steps from the knowledge
        base into a specific, actionable reference for the current request.
        """
        if not self.provider:
            return self.format_few_shot_prompt(match)

        key = match.get("key", "")
        steps_detail = match.get("last_steps_detail", [])
        steps = match.get("steps", [])

        if not steps_detail and not steps:
            return ""

        # Construct generic reference first
        generic_prompt = self.format_few_shot_prompt(match)

        prompt_parts = [
            f"You are given a previously successful workflow for the task: '{key}'.\n",
            "Adapt this generic workflow to fit the NEW current user request.\n",
            "Rules:\n",
            "- Extract specific parameters (paths, names, URLs, etc.) from the new request or history.\n",
            "- Replace the old parameters in the generic workflow with the new ones.\n",
            "- Keep the output concise, focusing purely on the modified steps.\n",
            "- Output a markdown formatted reference list of steps.\n\n",
        ]

        if history:
            prompt_parts.append("Recent conversation history (for additional context):\n")
            for msg in history[-5:]:
                role = msg.get("role", "unknown")
                content = msg.get("content", "")
                if isinstance(content, str):
                    prompt_parts.append(f"[{role}]: {content[:500]}\n")
                elif isinstance(content, list):
                    text_parts = [b.get("text", "") for b in content if b.get("type") == "text"]
                    text_content = " ".join(text_parts)
                    prompt_parts.append(f"[{role}]: {text_content[:500]}\n")

        prompt_parts.append(f"\nUser request: {current_request}\n")
        prompt_parts.append(f"\nGeneric workflow to adapt:\n{generic_prompt}\n\nAdapted workflow:")
        prompt = "".join(prompt_parts)

        try:
            response = await self.provider.chat(
                messages=[{"role": "user", "content": prompt}],
                model=self.model,
                temperature=0.1,
                max_tokens=300,
            )
            content = response.content or ""
            content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL)
            adapted = content.strip()
            if adapted:
                logger.info(f"KnowledgeWorkflow: successfully adapted knowledge for '{key}'")
                return f"## Contextual Reference: Adapted from '{key}'\n\n{adapted}"
        except Exception as e:
            logger.warning(f"KnowledgeWorkflow: adaptation failed: {e}")

        # Fallback to the generic prompt if LLM fails or returns empty
        return generic_prompt

    def get_match_stats(self, match: dict) -> dict:
        """Get formatted stats for a knowledge match (for display in prompts)."""
        success = match.get("success_count", 0)
        fail = match.get("fail_count", 0)
        total = success + fail
        rate = (success / total * 100) if total > 0 else 100
        return {
            "success_count": success,
            "fail_count": fail,
            "total": total,
            "rate": rate,
            "use_count": match.get("use_count", 0),
        }

    # ----------------------------------------------------------------
    # 8. Skill Upgrade Suggestion
    # ----------------------------------------------------------------

    def should_suggest_skill_upgrade(self, key: str) -> bool:
        """Check if a knowledge entry should be suggested for skill upgrade.

        Criteria: success_count >= 3 (frequently used and proven reliable).
        """
        if not self.knowledge_store:
            return False
        task = self.knowledge_store.find_task(key)
        if not task:
            return False
        return task.get("success_count", 0) >= 3

    @staticmethod
    def format_skill_upgrade_prompt(match: dict, lang: str | None = None) -> str:
        """Format the skill upgrade suggestion prompt."""
        return msg("skill_upgrade_prompt", lang=lang,
                   key=match.get("key", ""),
                   count=str(match.get("success_count", 0)))

    # ----------------------------------------------------------------
    # 9. Silent Steps Update (P1)
    # ----------------------------------------------------------------

    def silent_update_steps(self, key: str, tool_calls: list[dict]) -> bool:
        """Silently update steps_detail for a task after successful execution.

        Called during implicit feedback (success path) to keep the knowledge
        base's step details current without prompting the user.

        Args:
            key: Task key.
            tool_calls: The tool calls from the latest execution.

        Returns:
            True if updated, False if key not found or no store.
        """
        if not self.knowledge_store or not tool_calls:
            return False
        result = self.knowledge_store.update_steps_detail(key, tool_calls)
        if result:
            logger.debug(f"KnowledgeWorkflow: silent steps update for '{key}'")
        return result

    # ----------------------------------------------------------------
    # 10. Knowledge Base Management Commands (P2)
    # ----------------------------------------------------------------

    def format_kb_list(self, lang: str | None = None) -> str:
        """Format a human-readable list of all knowledge base entries."""
        if not self.knowledge_store:
            return msg("kb_list_empty", lang=lang)

        tasks = self.knowledge_store.get_all_tasks()
        if not tasks:
            return msg("kb_list_empty", lang=lang)

        lines = [msg("kb_list_header", lang=lang)]
        for i, t in enumerate(tasks, 1):
            key = t.get("key", "?")
            version = t.get("version", 1)
            sc = t.get("success_count", 0)
            fc = t.get("fail_count", 0)
            total = sc + fc
            rate = int(sc / total * 100) if total > 0 else 100
            use_count = t.get("use_count", 0)
            lines.append(
                f"{i}. **{key}** — v{version} | "
                f"成功率 {rate}% | 使用 {use_count} 次"
            )
        return "\n".join(lines)

    def delete_knowledge(self, key: str, lang: str | None = None) -> str:
        """Delete a knowledge base entry by key. Returns user-facing message."""
        if not self.knowledge_store:
            return msg("kb_delete_not_found", lang=lang, key=key)
        if self.knowledge_store.delete_task(key):
            logger.info(f"KnowledgeWorkflow: deleted knowledge entry '{key}'")
            return msg("kb_delete_success", lang=lang, key=key)
        return msg("kb_delete_not_found", lang=lang, key=key)

    def cleanup_knowledge(self, lang: str | None = None) -> str:
        """Find and merge duplicate/similar knowledge base entries.

        Returns a user-facing message with cleanup stats.
        """
        if not self.knowledge_store:
            return msg("kb_cleanup_result", lang=lang, merged="0", deleted="0")

        tasks = self.knowledge_store.get_all_tasks()
        merged_count = 0
        deleted_keys: set[str] = set()

        # Compare each pair; skip already-deleted entries
        for i, t1 in enumerate(tasks):
            k1 = t1.get("key", "")
            if k1 in deleted_keys:
                continue
            for t2 in tasks[i + 1:]:
                k2 = t2.get("key", "")
                if k2 in deleted_keys:
                    continue
                # Use tokenize similarity
                w1 = set(tokenize_key(k1))
                w2 = set(tokenize_key(k2))
                if not w1 or not w2:
                    continue
                score = len(w1 & w2) / len(w1 | w2)
                if score >= 0.5:
                    # Merge t2 into t1 (keep the one with more successes)
                    keep, discard = (t1, t2) if t1.get("success_count", 0) >= t2.get("success_count", 0) else (t2, t1)
                    self.knowledge_store.merge_task(
                        keep.get("key", ""),
                        new_steps=discard.get("steps"),
                        new_result_summary=discard.get("result_summary"),
                    )
                    self.knowledge_store.delete_task(discard.get("key", ""))
                    deleted_keys.add(discard.get("key", ""))
                    merged_count += 1
                    logger.info(
                        f"KnowledgeWorkflow cleanup: merged '{discard.get('key')}' "
                        f"into '{keep.get('key')}'"
                    )

        return msg(
            "kb_cleanup_result", lang=lang,
            merged=str(merged_count), deleted=str(len(deleted_keys)),
        )

