"""Knowledge Workflow Engine.

Implements the user's desired knowledge base workflow:
1. Extract a task Key from user request (via lightweight LLM call)
2. Code-level comparison against stored knowledge base entries
3. If match found: ask user to reuse or re-execute
4. After task completion: prompt to save/update knowledge base
"""

from typing import Any
import re

from loguru import logger

from nanobot.agent.i18n import msg
from nanobot.agent.task_knowledge import TaskKnowledgeStore


# --- User command recognition ---
# All recognized forms of "use knowledge base" commands
_USE_COMMANDS = {
    # Chinese
    "直接用", "用知识库", "用", "使用知识库", "使用", "直接使用",
    # English
    "use", "reuse", "yes",
}

# All recognized forms of "re-execute" commands
_REDO_COMMANDS = {
    # Chinese
    "重新执行", "重新", "重新处理", "重做",
    # English
    "redo", "re-execute", "rerun", "again",
}

# All recognized forms of "save confirmation" commands
_SAVE_COMMANDS = {
    # Chinese
    "是", "好", "是的", "好的", "保存", "存",
    # English
    "yes", "ok", "save", "y",
}

# All recognized forms of "upgrade to skill" commands
_UPGRADE_COMMANDS = {
    # Chinese
    "升级", "升级skill", "升",
    # English
    "upgrade", "upgrade skill",
}


class KnowledgeWorkflow:
    """Knowledge base workflow engine.

    Responsibilities:
    1. Call lightweight LLM to extract a Key from user request
       (Chinese ≤50 chars, English ≤200 chars)
    2. Code-level comparison of Key against knowledge base entries
       (exact match → substring match → common-word similarity)
    3. Format prompts for user interaction
    4. Save/update knowledge base entries
    """

    def __init__(
        self,
        provider: Any = None,
        model: str | None = None,
        workspace: Any = None,
    ):
        self.provider = provider
        self.model = model
        self.workspace = workspace
        self.knowledge_store = TaskKnowledgeStore(workspace) if workspace else None

    # ----------------------------------------------------------------
    # 1. Key Extraction (lightweight LLM call)
    # ----------------------------------------------------------------

    async def extract_key(self, user_request: str) -> str:
        """Extract a task key from user request using a lightweight LLM call.

        The key should be:
        - Chinese: ≤50 characters
        - English: ≤200 characters
        - A concise description of the task's core intent

        Returns:
            Extracted key string, or a truncated version of the request as fallback.
        """
        if not self.provider:
            return self._fallback_key(user_request)

        prompt = (
            "Extract a concise task description from the user request below. "
            "Rules:\n"
            "- If the request is in Chinese, output ≤50 Chinese characters\n"
            "- If the request is in English, output ≤200 English characters\n"
            "- Output ONLY the key text, nothing else\n"
            "- Focus on the core action and target\n\n"
            f"User request: {user_request}\n\n"
            "Key:"
        )

        try:
            response = await self.provider.chat(
                messages=[{"role": "user", "content": prompt}],
                model=self.model,
                temperature=0.1,
                max_tokens=100,
            )
            content = response.content or ""
            # Strip <think>...</think> tags which are generated by reasoning models
            content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL)
            key = content.strip().strip('"').strip("'")
            if key:
                logger.info(f"KnowledgeWorkflow: extracted key = '{key}'")
                return key
        except Exception as e:
            logger.warning(f"KnowledgeWorkflow: key extraction failed: {e}")

        return self._fallback_key(user_request)

    def _fallback_key(self, user_request: str) -> str:
        """Fallback key extraction without LLM — simple truncation."""
        # Heuristic: if mostly CJK chars, limit to 50; otherwise 200
        cjk_count = sum(1 for c in user_request if '\u4e00' <= c <= '\u9fff')
        limit = 50 if cjk_count > len(user_request) * 0.3 else 200
        return user_request[:limit].strip()

    # ----------------------------------------------------------------
    # 2. Knowledge Base Matching (pure code, no LLM)
    # ----------------------------------------------------------------

    def match_knowledge(self, key: str) -> dict[str, Any] | None:
        """Match extracted key against knowledge base entries.

        Matching strategy (in order of priority):
        1. Exact match (key strings identical)
        2. Substring match (one key contains the other)
        3. Common-word similarity (>= 50% shared words)

        Returns:
            Matched task entry dict, or None if no match found.
        """
        if not self.knowledge_store:
            return None

        tasks = self.knowledge_store.get_all_tasks()
        if not tasks:
            return None

        key_lower = key.lower().strip()

        # Pass 1: Exact match
        for task in tasks:
            task_key = task.get("key", "").lower().strip()
            if task_key == key_lower:
                logger.info(f"KnowledgeWorkflow: exact match found: '{task_key}'")
                return task

        # Pass 2: Substring match
        best_substring: dict | None = None
        best_ratio = 0.0
        for task in tasks:
            task_key = task.get("key", "").lower().strip()
            if not task_key:
                continue
            if key_lower in task_key or task_key in key_lower:
                shorter = min(len(key_lower), len(task_key))
                longer = max(len(key_lower), len(task_key))
                ratio = shorter / longer if longer > 0 else 0
                if ratio > best_ratio:
                    best_ratio = ratio
                    best_substring = task
        if best_substring and best_ratio >= 0.5:
            logger.info(
                f"KnowledgeWorkflow: substring match found: "
                f"'{best_substring.get('key')}' (ratio={best_ratio:.2f})"
            )
            return best_substring

        # Pass 3: Common-word similarity
        key_words = set(self._tokenize(key_lower))
        if not key_words:
            return None

        best_word_match: dict | None = None
        best_word_score = 0.0
        for task in tasks:
            task_key = task.get("key", "").lower().strip()
            task_words = set(self._tokenize(task_key))
            if not task_words:
                continue
            common = key_words & task_words
            union = key_words | task_words
            score = len(common) / len(union) if union else 0
            if score > best_word_score:
                best_word_score = score
                best_word_match = task

        if best_word_match and best_word_score >= 0.5:
            logger.info(
                f"KnowledgeWorkflow: word-similarity match found: "
                f"'{best_word_match.get('key')}' (score={best_word_score:.2f})"
            )
            return best_word_match

        logger.debug(f"KnowledgeWorkflow: no match found for key '{key}'")
        return None

    def _tokenize(self, text: str) -> list[str]:
        """Tokenize text for word-similarity matching.

        For Chinese text: uses jieba word segmentation (falls back to char-level).
        For English text: splits by whitespace, filters short words.
        """
        # Check if text is predominantly CJK
        cjk_count = sum(1 for c in text if '\u4e00' <= c <= '\u9fff')
        if cjk_count > len(text) * 0.3:
            # Chinese: use jieba if available
            try:
                import jieba
                words = jieba.lcut(text)
                # Filter: keep words ≥2 chars, remove pure whitespace/punctuation
                return [w.strip() for w in words if len(w.strip()) >= 2]
            except ImportError:
                # Fallback: each CJK char as token
                tokens: list[str] = []
                for char in text:
                    if '\u4e00' <= char <= '\u9fff':
                        tokens.append(char)
                return tokens
        else:
            # English: split by whitespace, filter short words
            return [w for w in text.split() if len(w) > 1]

    # ----------------------------------------------------------------
    # 3. User Command Recognition
    # ----------------------------------------------------------------

    @staticmethod
    def is_use_command(text: str) -> bool:
        """Check if user input means 'use knowledge base result'."""
        return text.strip().lower() in _USE_COMMANDS

    @staticmethod
    def is_redo_command(text: str) -> bool:
        """Check if user input means 're-execute the task'."""
        return text.strip().lower() in _REDO_COMMANDS

    @staticmethod
    def is_save_confirm(text: str) -> bool:
        """Check if user input means 'confirm save to knowledge base'."""
        return text.strip().lower() in _SAVE_COMMANDS

    @staticmethod
    def is_upgrade_command(text: str) -> bool:
        """Check if user input means 'confirm skill upgrade'."""
        return text.strip().lower() in _UPGRADE_COMMANDS
    # ----------------------------------------------------------------
    # 4. Prompt Formatting
    # ----------------------------------------------------------------

    @staticmethod
    def format_match_prompt(match: dict, lang: str | None = None) -> str:
        """Format the knowledge-match prompt for the user."""
        key = match.get("key", "unknown")
        return msg("knowledge_match_prompt", lang=lang, key=key)

    @staticmethod
    def format_save_prompt(lang: str | None = None) -> str:
        """Format the save-to-knowledge-base prompt."""
        return msg("save_prompt", lang=lang)

    @staticmethod
    def format_save_confirmed(lang: str | None = None) -> str:
        """Format the save-confirmed message."""
        return msg("save_confirmed", lang=lang)

    # ----------------------------------------------------------------
    # 5. Knowledge Base Save / Update
    # ----------------------------------------------------------------

    async def save_to_knowledge(
        self,
        key: str,
        steps: list[dict],
        user_request: str,
        result_summary: str = "",
    ) -> bool:
        """Save or update a task in the knowledge base.

        Args:
            key: Task key (extracted by extract_key).
            steps: List of tool call dicts [{tool, args}, ...].
            user_request: Original user request text.
            result_summary: Summary of the task result.

        Returns:
            True if saved successfully.
        """
        if not self.knowledge_store:
            logger.warning("KnowledgeWorkflow: no knowledge store available")
            return False

        try:
            existing = self.knowledge_store.find_task(key)
            if existing:
                # Update: overwrite steps and result
                existing["steps"] = steps
                existing["result_summary"] = result_summary or "Task completed"
                self.knowledge_store.update_task(key, result_summary or "Task reused")
                logger.info(f"KnowledgeWorkflow: updated knowledge for key='{key}'")
            else:
                self.knowledge_store.add_task(
                    key=key,
                    description=user_request[:100],
                    steps=steps,
                    params={},
                    result_summary=result_summary or "Task completed",
                )
                logger.info(f"KnowledgeWorkflow: saved new knowledge for key='{key}'")
            return True
        except Exception as e:
            logger.error(f"KnowledgeWorkflow: save failed: {e}")
            return False

    def get_knowledge_result(self, match: dict, lang: str | None = None) -> str:
        """Format and return the stored result of a matched knowledge entry.

        If the match has a result_summary, returns that.
        Otherwise returns step names.
        """
        result_summary = match.get("result_summary", "")
        if result_summary:
            return msg("knowledge_result_header", lang=lang, result=result_summary)

        # Fallback: list the steps
        steps = match.get("steps", [])
        if steps:
            step_names = []
            for s in steps:
                if isinstance(s, dict):
                    step_names.append(s.get("tool", str(s)))
                else:
                    step_names.append(str(s))
            steps_text = "\n".join(f"  {i+1}. {name}" for i, name in enumerate(step_names))
            return msg("knowledge_result_header", lang=lang, result=steps_text)

        return msg("knowledge_no_params", lang=lang)

    # ----------------------------------------------------------------
    # 6. Outcome Tracking (implicit feedback)
    # ----------------------------------------------------------------

    # Negative feedback patterns — if user's next message matches,
    # the previous task is recorded as a failure.
    _NEGATIVE_FEEDBACK = {
        # Chinese
        "不对", "错了", "重来", "重做", "不行", "有问题", "再试",
        # English
        "wrong", "incorrect", "redo", "try again", "not right", "fix it",
    }

    @classmethod
    def is_negative_feedback(cls, text: str) -> bool:
        """Check if user message implies the previous task failed."""
        t = text.strip().lower()
        return any(neg in t for neg in cls._NEGATIVE_FEEDBACK)

    def record_outcome(self, key: str, success: bool) -> None:
        """Record task outcome (success or failure) in knowledge base."""
        if not self.knowledge_store:
            return
        if success:
            self.knowledge_store.record_success(key)
            logger.info(f"KnowledgeWorkflow: recorded success for '{key}'")
        else:
            self.knowledge_store.record_failure(key)
            logger.info(f"KnowledgeWorkflow: recorded failure for '{key}'")

    # ----------------------------------------------------------------
    # 7. Few-shot Prompt Generation (for local model accuracy)
    # ----------------------------------------------------------------

    def format_few_shot_prompt(self, match: dict) -> str:
        """Generate a few-shot reference prompt from a high-success knowledge entry.

        This is injected into the system message when a user chooses "redo" on a
        matched task, giving the local LLM a reference path to follow.

        Returns:
            A formatted prompt string, or empty string if no useful detail available.
        """
        key = match.get("key", "")
        steps_detail = match.get("last_steps_detail", [])
        steps = match.get("steps", [])
        result_summary = match.get("result_summary", "")
        success_count = match.get("success_count", 0)
        use_count = match.get("use_count", 0)

        if not steps_detail and not steps:
            return ""

        lines = [
            f"## Reference: Previously successful execution of '{key}'",
            f"(Success: {success_count}/{use_count} executions)",
            "",
        ]

        if steps_detail:
            lines.append("### Steps taken:")
            for i, step in enumerate(steps_detail, 1):
                tool = step.get("tool", "unknown")
                args = step.get("args", {})
                result = step.get("result", "")
                args_str = ", ".join(f"{k}={v!r}" for k, v in args.items()) if isinstance(args, dict) else str(args)
                lines.append(f"{i}. `{tool}({args_str})`")
                if result:
                    lines.append(f"   → {result[:200]}")
        elif steps:
            lines.append("### Tools used:")
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    lines.append(f"{i}. `{step.get('tool', str(step))}`")
                else:
                    lines.append(f"{i}. `{step}`")

        if result_summary:
            lines.extend(["", f"### Final result: {result_summary}"])

        lines.extend([
            "",
            "Use this as a reference. Adapt parameters to the current request.",
        ])
        return "\n".join(lines)

    def get_match_stats(self, match: dict) -> dict:
        """Get formatted stats for a knowledge match (for display in prompts)."""
        success = match.get("success_count", 0)
        fail = match.get("fail_count", 0)
        total = success + fail
        rate = (success / total * 100) if total > 0 else 100
        return {
            "success_count": success,
            "fail_count": fail,
            "total": total,
            "rate": rate,
            "use_count": match.get("use_count", 0),
        }

    # ----------------------------------------------------------------
    # 8. Skill Upgrade Suggestion
    # ----------------------------------------------------------------

    def should_suggest_skill_upgrade(self, key: str) -> bool:
        """Check if a knowledge entry should be suggested for skill upgrade.

        Criteria: success_count >= 3 (frequently used and proven reliable).
        """
        if not self.knowledge_store:
            return False
        task = self.knowledge_store.find_task(key)
        if not task:
            return False
        return task.get("success_count", 0) >= 3

    @staticmethod
    def format_skill_upgrade_prompt(match: dict, lang: str | None = None) -> str:
        """Format the skill upgrade suggestion prompt."""
        return msg("skill_upgrade_prompt", lang=lang,
                   key=match.get("key", ""),
                   count=str(match.get("success_count", 0)))

